/* invoice-premium.test.js — "Deshwali Premium Invoice": the firm's quotation
   letterhead (PDF DM/QT/2026-27/922, 18-09-2026) as a tax invoice.
   Run:  node dashboard/v2/invoice-premium.test.js

   Pins the layout the owner pointed at — navy band, gold rule, contact line,
   boxed strip, From/To boxes, navy table with packing, totals block, words,
   terms list, bank + declaration boxes, seal — and the same honesty rules as
   every design: nothing invented, nothing empty printed, units through
   units-core, IRN/QR only when real, export block only when there is one. */
const fs = require('fs'), path = require('path');
const T = require(path.join(__dirname, 'invoice-templates.js'));
let pass = 0, fail = 0; const fails = [];
const ok = (n, c) => { if (c) pass++; else { fail++; fails.push(n); } };
const seller = { name: 'DESHWALI MINERALS', short: 'Deshwali', sealText: 'BORUNDA, GOTAN', logoMark: 'gem', lockup: '/v2/deshwali-lockup.svg?v=1', address: 'Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan', state: 'Rajasthan (08)', gstin: '08NLIPS9801K1Z5', tel: '8875020202, 9460767676', email: 'deshwaliminerals@gmail.com', website: 'www.deshwaliminerals.com', product: 'Manufacturer & Exporter of Premium Quick Lime and Hydrated Lime', logo: '/v2/deshwali-logo.png', iec: 'NLIPS9801K', lut: 'AD080826023319U', bank: 'HDFC Bank', bankBranch: 'Merta City', accNo: '50200089605146', ifsc: 'HDFC0002670', upi: '8875020202@hdfcbank', jurisdiction: 'RAJASTHAN', terms: ['Goods once sold will not be taken back.', 'Interest @ 18% p.a. will be charged if the payment is not made with in the 30days.', "Subject to 'RAJASTHAN' Jurisdiction only."] };
const BASE = { seller, buyer: { name: 'PHANTOM CHEMICALS', gstin: '19FNSPA3224G1ZY', address: 'Near More Shopping Mall, Haroa Road, Haroa, North 24 Parganas, West Bengal – 743425', state: 'West Bengal (19)', phone: '7872532502', email: '' },
  hsn: '25221000', inv: '2/2026-27', date: '2026-09-18', product: 'Quicklime (Calcium Oxide) — Lumps', desc: 'Industrial grade · high calcium, low silica · sized 20–80 mm', packing: '50 kg HDPE bags', qty: 42, unit: 'MT', rate: 5500, rateUnit: 'Ton', veh: 'RJ19GA1234', transport: 'By Road', station: 'Haroa, W.B.', eway: '', gstR: 5,
  taxable: 231000, cgst: 0, sgst: 0, igst: 11550, interState: true, total: 242550, roundOff: 0, grand: 242550, words: 'Rupees Two Lakh Forty Two Thousand Five Hundred Fifty Only' };
const R = (extra, cfg) => T.render(Object.assign({}, BASE, extra || {}), Object.assign({ template: 'premium' }, cfg || {}));
const h = R(), t = h.replace(/<[^>]+>/g, ' ');

console.log('\n═══ Deshwali Premium Invoice ═══');
const reg = T.get('premium');
ok('registered as "Deshwali Premium Invoice", fixed colours (not accentable), with despatch fields', reg && reg.name === 'Deshwali Premium Invoice' && reg.accentable === false && reg.despatch === true);
ok('the existing designs are untouched (registry order; blueink added after, 19-09-2026)', T.TEMPLATES.map(x => x.id).join(',') === 'gst,modern,business,detailed,industrial,premium,blueink');
ok('navy band (#0E2A47, sampled from the PDF): gem + two-line wordmark left, TAX INVOICE + copy label right — nothing else in it', /\.band\{background:#0E2A47/.test(h) && /class="band"/.test(h) && /TAX INVOICE/.test(t) && /Original for Recipient/.test(t) && !/class="t"/.test(h.slice(h.indexOf('class="band"'), h.indexOf('class="contact"'))));
ok('the product line sits under the band above the contact line, not inside the band', /class="contact"><div class="pl">Manufacturer &amp; Exporter of Premium Quick Lime and Hydrated Lime<\/div>/.test(h));
ok('gold rule under the band', /border-bottom:3px solid #C9A227/.test(h));
ok('band geometry as measured on the reference (110 dpi → CSS px ×0.873): 79px tall on the 820 sheet, edge to edge, lockup 34px, 5.3% inset, title 16.5px', /\.band\{[^}]*padding:22px 5\.4% 22px 5\.3%;min-height:79px/.test(h) && /\.band \.lockup\{height:34px!important/.test(h) && /\.band \.ti \.w\{font-size:16\.5px/.test(h) && /@media print\{\.sheet\{max-width:none;padding:0 0 6mm;min-height:100vh/.test(h));
ok('the whole page is set at the reference\'s density: body 8.7px, box names 10.5px, table cells 8.7px, totals rows at 2.5px pads on line-height 1.3 (owner, 18-09-2026: tight, then "give some above or below spacing", then "a little bit line height"), terms rows 6px pads', /body\{[^}]*font-size:8\.7px/.test(h) && /\.box \.nm\{font-size:10\.5px/.test(h) && /\.it td\{padding:7px 7px;[^}]*font-size:8\.7px/.test(h) && /\.tot td\{padding:2\.5px 10px;line-height:1\.3;/.test(h) && /\.tc td\{padding:6px 0/.test(h));
ok('the band prints the firm\'s letterhead LOCKUP (the owner\'s SVG: diamond + wordmark, white on transparent) with alt text, and no separate text wordmark', /<img class="lockup" src="[^"]*deshwali-lockup\.svg\?v=1" alt="DESHWALI MINERALS"/.test(h) && !/class="n">/.test(h));
ok('the lockup file is the owner\'s vector, white with #ECECEC facets, no scripts', (function () { const svg = fs.readFileSync(path.join(__dirname, 'deshwali-lockup.svg'), 'utf8'); return /viewBox="0 0 284 51"/.test(svg) && /fill="#ECECEC"/.test(svg) && (svg.match(/fill="white"/g) || []).length >= 10 && !/<script|<image|href=/.test(svg); })());
ok('a firm WITHOUT a lockup gets its own logo printed white (facets only with logoMark gem) beside the two-line wordmark', (function () { const x = R({ seller: Object.assign({}, seller, { lockup: '' }) }); return /class="lg"[^>]*><img src="[^"]*deshwali-logo\.png"[^>]*filter:brightness\(0\) invert\(1\)/.test(x) && /viewBox="0 0 1000 655"/.test(x) && /class="n">DESHWALI<br>MINERALS</.test(x); })());
ok('another firm\'s logo gets a clean white silhouette (no facet lines); a firm with no logo and no lockup gets the vector gem', !/viewBox="0 0 1000 655"/.test(R({ seller: Object.assign({}, seller, { lockup: '', logoMark: '', logo: '/v2/gotan-logo.png' }) })) && /<svg class="gem"/.test(R({ seller: Object.assign({}, seller, { lockup: '', logo: '' }) })));
ok('contact line: website · e-mail · phones in the PDF\'s form (+91 88750 20202, +91 94607 67676)', /www\.deshwaliminerals\.com/.test(t) && /deshwaliminerals@gmail\.com/.test(t) && /\+91 88750 20202, \+91 94607 67676/.test(t));
ok('the boxed strip: Invoice No. · Date · Vehicle No. · Place of supply; despatch strip carries Transport · Vehicle · Station · GR/RR', /Invoice No\./.test(t) && /2\/2026-27/.test(t) && /18-09-2026/.test(t) && /RJ19GA1234/.test(t) && /Place of supply/.test(t) && /West Bengal \(19\)/.test(t));
ok('the third cell prefers the due date, then the e-way number, then the vehicle', /Due date/.test(R({ due: '2026-10-03' }).replace(/<[^>]+>/g, ' ')) && /E-Way Bill No\.[\s\S]*791656947547/.test(R({ eway: '791656947547' }).replace(/<[^>]+>/g, ' ')));
ok('FROM — SUPPLIER and TO — BUYER boxes with GSTIN, State, PAN, Mobile', /From — Supplier/.test(t) && /To — Buyer/.test(t) && /08NLIPS9801K1Z5/.test(t) && /19FNSPA3224G1ZY/.test(t) && /Rajasthan \(08\)/.test(t) && /FNSPA3224G/.test(t) && /7872532502/.test(t));
ok('supplier address breaks like the reference: street + town, then State – PIN, India', /class="ad">Near Dharam Kanta Gotan Road, Borunda\nRajasthan – 342604, India</.test(h));
ok('a hand-broken address is kept as written; a state-less one gets just the PIN line', /class="ad">Plot 4\nMIDC Phase II\nPune</.test(R({ seller: Object.assign({}, seller, { address: 'Plot 4\nMIDC Phase II\nPune', state: '' }) })) && /class="ad">Plot 4, Pune\n411001, India</.test(R({ seller: Object.assign({}, seller, { address: 'Plot 4, Pune 411001', state: '', pin: '411001' }) })));
ok('no E-mail line in either box (the supplier e-mail is on the contact line, as in the reference); a buyer with an e-mail and a contact gets Attn. + E-mail; no Packing column when no line has packing', !/E-mail:/.test(h.slice(h.indexOf('From — Supplier'), h.indexOf('class="meta" style="margin-top:0"'))) && (function () { const x = R({ buyer: Object.assign({}, BASE.buyer, { email: 'buyer@phantom.in', contact: 'Mr. Aroof Ahmed' }) }); const b = x.slice(x.indexOf('To — Buyer')); return /Attn\.:<\/span><b>Mr\. Aroof Ahmed</.test(b) && /E-mail:<\/span><b>buyer@phantom\.in</.test(b); })() && !/Packing/.test(R({ packing: '' }).replace(/<[^>]+>/g, ' ')));
ok('navy table: Sr · Description · HSN · Packing · Qty (MT) · Rate / Ton · Amount', /Description/.test(t) && /HSN/.test(t) && /Packing/.test(t) && /50 kg HDPE bags/.test(t) && /Qty \(MT\)/.test(t) && /Rate \/ Ton/.test(t));
ok('description in navy bold with the grey sub-line', /class="dn">Quicklime \(Calcium Oxide\) — Lumps</.test(h) && /class="ds">Industrial grade/.test(h));
ok('the line: 42 · 5,500.00 · 2,31,000.00 — no INR prefix on money (owner, 18-09-2026)', /5,500\.00/.test(t) && /2,31,000\.00/.test(t) && !/INR /.test(h.slice(h.indexOf('<table class="it"'), h.indexOf('class="words"'))));
ok('totals block: value of goods with its arithmetic (tonnes to three decimals), IGST @ 5.00 % (HSN 25221000), total payable — and NO quantity row', /Value of goods \(\s*42 MT\s*× 5,500\/Ton\)/.test(t) && /class="qtytot[^"]*">42 MT</.test(h) && /IGST @ 5\.00 % \(HSN 25221000\)/.test(t) && /11,550\.00/.test(t) && /Total payable \(goods incl\. GST\)/.test(t) && /2,42,550\.00/.test(t) && !/Total quantity/.test(t));
ok('table cells like the reference: centred headers, HSN 25221000 centred, quantity 42.000 bold centred, amount bold right', /th\{[^}]*text-align:center/.test(h) && /<td class="c">25221000<\/td>/.test(h) && /<td class="q">42\.000<\/td>/.test(h) && /<td class="r"><b>2,31,000\.00<\/b>/.test(h));
ok('supplier box lines: GSTIN · State, PAN · IEC, Mobile — values in regular weight after grey labels', /PAN:<\/span><b>NLIPS9801K<\/b><\/span><span class="kv"><span>IEC:<\/span><b>NLIPS9801K<\/b>/.test(h) && /Mobile:<\/span><b>\+91 88750 20202, \+91 94607 67676<\/b>/.test(h));
ok('totals: the figure column fits its widest figure (width:1%, nowrap) so each label ends ~40px before its figure (20px was "too close") — owner, 18-09-2026', /\.tot td\.v\{[^}]*width:1%;white-space:nowrap;padding-left:30px\}/.test(h) && !/\.tot td\.l\{[^}]*width:\d+%/.test(h));
ok('amount in words says what it includes', /Rupees Two Lakh Forty Two Thousand Five Hundred Fifty Only \(inclusive of IGST\)/.test(t));
ok('a buyer contact prints as Attn.', /Attn\.:<\/span><b>Md\. Arman Khan Jony<\/b>/.test(R({ buyer: Object.assign({}, BASE.buyer, { contact: 'Md. Arman Khan Jony' }) })));
ok('intra-state prints CGST + SGST instead', (function () { const x = R({ interState: false, igst: 0, cgst: 5775, sgst: 5775, buyer: Object.assign({}, BASE.buyer, { gstin: '08BPLPS6684F1Z6', state: 'Rajasthan (08)' }) }).replace(/<[^>]+>/g, ' '); return /CGST @ 2\.50 %/.test(x) && /SGST @ 2\.50 %/.test(x) && !/IGST/.test(x); })());
ok('amount in words as "Rupees … Only" — no "Indian" (owner, 18-09-2026)', /Amount in words:\s*Rupees Two Lakh Forty Two Thousand Five Hundred Fifty Only/.test(t) && !/Indian Rupees/.test(t));
ok('terms as a two-column list — a Label: text term prints its label as the key, an unlabelled one its number (1., 3.) — the jurisdiction term included', /class="k">1\.</.test(h) && /class="k">3\.</.test(h) && /class="k">Payment Terms</.test(R({ seller: Object.assign({}, seller, { terms: ['Payment Terms: 30 days net.'] }) })) && /Subject to 'RAJASTHAN' Jurisdiction only\./.test(t));
ok('a term written "LABEL: text" uses its own label', /Price basis/.test(R({}, { terms: ['Price basis: Goods ex-works Borunda.'] }).replace(/<[^>]+>/g, ' ')));
ok('Bank Details — for payment box with account name, bank, A/C, IFSC, UPI', /Bank Details — for payment/.test(t) && /Account name: DESHWALI MINERALS/.test(t) && /HDFC Bank, Merta City/.test(t) && /A\/C No\.: 50200089605146/.test(t) && /IFSC: HDFC0002670/.test(t) && /UPI: 8875020202@hdfcbank/.test(t));
ok('no bank box for a firm with nothing on file', !/Bank Details/.test(R({ seller: Object.assign({}, seller, { bank: '', accNo: '', upi: '' }) }).replace(/<[^>]+>/g, ' ')));
ok('Declaration box replaces the quotation\'s "To confirm this order"', /Declaration/.test(t) && /We declare that this invoice shows the actual price/.test(t) && !/To confirm this order/.test(t));
ok('no "Dear Sir" letter — this is an invoice, not an offer', !/Dear Sir/.test(t) && !/Thank you for your enquiry/.test(t));
ok('"For DESHWALI MINERALS", a round seal, "Authorised Signatory & Seal"', /For DESHWALI MINERALS/.test(t) && /<svg class="seal"/.test(h) && /textPath/.test(h) && /Authorised Signatory &amp; Seal/.test(h));
ok('the seal: firm name on the top arc, the stamp\'s own line on the bottom arc, stars and dash-dot marks — never an invented registration', (function () { const si = h.indexOf('<svg class="seal"'); const sv = h.slice(si, h.indexOf('</svg>', si)); return /sealTop[\s\S]*DESHWALI MINERALS/.test(sv) && /sealBot[\s\S]*BORUNDA, GOTAN</.test(sv) && !/RAJASTHAN/.test(sv) && (sv.match(/<polygon /g) || []).length === 2 && (sv.match(/<line /g) || []).length === 4 && !/Regd\. No|Reg\. No|GSTIN/.test(sv); })());
ok('the seal is the reference stamp, measured: rings 49.1/1.75 · 46.6/.8 · 33.7/.8 · 32/.6, name on a 39.3 baseline in 7.8, stamp line hung from 45.0 in 6.2, stars at r 41.4, marks at y 29/69, ink #0A1F5C, 64px', (function () { const si = h.indexOf('<svg class="seal"'); const sv = h.slice(si, h.indexOf('</svg>', si)); return /width="64" height="64"/.test(sv) && /r="49.1" stroke-width="1.75"/.test(sv) && /r="46.6" stroke-width=".8"/.test(sv) && /r="33.7" stroke-width=".8"/.test(sv) && /r="32" stroke-width=".6"/.test(sv) && /M10.7,50 a39.3,39.3 0 0,1 78.6,0/.test(sv) && /M5,50 a45,45 0 0,0 90,0/.test(sv) && /font-size="7.8"[^>]*><textPath href="#sealTop"/.test(sv) && /font-size="6.2"[^>]*><textPath href="#sealBot"/.test(sv) && /points="8.60,46.70/.test(sv) && /points="91.40,46.70/.test(sv) && /y1="29"/.test(sv) && /y1="69"/.test(sv) && (sv.match(/#0A1F5C/g) || []).length >= 6; })());
ok('the seal text is fitted to its arc: DESHWALI MINERALS opens to the reference\'s 140° span, a long name is compressed rather than clipped, a short stamp line is not stretched across the whole arc', (function () { const si = h.indexOf('<svg class="seal"'); const sv = h.slice(si, h.indexOf('</svg>', si)); const long = R({ seller: Object.assign({}, seller, { name: 'DESHWALI MINERALS AND CHEMICALS PRIVATE LIMITED' }) }); const li = long.indexOf('<svg class="seal"'); const lv = long.slice(li, long.indexOf('</svg>', li)); const top = sv.slice(sv.indexOf('#sealTop"'), sv.indexOf('</textPath>')), bot = sv.slice(sv.indexOf('#sealBot"'), sv.lastIndexOf('</textPath>')); return /startOffset="13\.7" textLength="96\.0" lengthAdjust="spacingAndGlyphs"/.test(top) && /startOffset="[\d.]+" textLength="[\d.]+" lengthAdjust="spacingAndGlyphs"/.test(lv) && /startOffset="33\.8" textLength="73\.7" lengthAdjust="spacingAndGlyphs"/.test(bot) && !/text-anchor="middle"/.test(sv); })());
ok('seal text is centred by construction (start offset = (half-circle − span)/2), not by text-anchor — Verdana on the owner\'s Mac drifted it clockwise on 18-09-2026', (function () { const si = h.indexOf('<svg class="seal"'); const sv = h.slice(si, h.indexOf('</svg>', si)); const m = sv.match(/startOffset="([\d.]+)" textLength="([\d.]+)"/g) || []; return m.length === 2 && m.every(function (x) { const n = x.match(/[\d.]+/g).map(Number); return n[0] > 0; }) && Math.abs((13.7 * 2 + 96.0) - Math.PI * 39.3) < 0.2 && Math.abs((33.8 * 2 + 73.7) - Math.PI * 45) < 0.2; })());
ok('on paper the sheet fills the page: signature block pushed to the bottom (print rule)', /@media print\{\.sheet\{[^}]*min-height:100vh[^}]*display:flex;flex-direction:column\}\.sheet \.in\{flex:1[^}]*\}\.sheet \.in \.close\{margin-top:auto/.test(h));
ok('a firm with no seal line falls back to city + state on the bottom arc', /sealBot[\s\S]*MERTA, RAJASTHAN/.test(R({ seller: Object.assign({}, seller, { sealText: '', city: 'Merta' }) })));
ok('footer: invoice no., date, "tax invoice under the CGST Rules, 2017" — no E&OE (owner, 18-09-2026)', /Invoice 2\/2026-27 · 18-09-2026 · This is a tax invoice under the CGST Rules, 2017\./.test(t) && !/Errors and omissions/.test(t));
ok('reverse charge and jurisdiction on the closing line', /Reverse charge: No/.test(t) && /Subject to RAJASTHAN jurisdiction/.test(t));
ok('no undefined / NaN / null', !/undefined|NaN|\bnull\b/.test(t));
ok('buyer markup is escaped', R({ buyer: Object.assign({}, BASE.buyer, { name: '<script>x</script>' }) }).includes('&lt;script&gt;'));
ok('A4 standalone document; narrow previews scale', /^<!DOCTYPE html>/.test(h) && /@page\{size:A4/.test(h) && /max-width:760px\)\{\.sheet\{zoom:\.7\}/.test(h));

console.log('═══ units, multi-line, e-invoice, export ═══');
const kg = R({ qty: 7650, unit: 'Kg', rate: 5300, rateUnit: 'Ton', billableQty: 7.65, billableUnit: 'Ton', taxable: 40545, igst: 2027.25, total: 42572.25, grand: 42572.25, packing: '', words: 'Rupees Forty Two Thousand Five Hundred Seventy Two and Paisa Twenty Five Only' }).replace(/<[^>]+>/g, ' ');
ok('a Kg line priced per Ton: Qty (Kg), Rate / Ton, the conversion note, 40,545.00', /Qty \(Kg\)/.test(kg) && /Rate \/ Ton/.test(kg) && /7,650 Kg = 7\.65 Ton × ₹5,300\.00/.test(kg) && /40,545\.00/.test(kg) && !/4,05,45,000/.test(kg));
const ml = R({ items: [{ hsn: '25221000', product: 'Quick Lime Powder', grade: 'Industrial Grade', packing: '50 KG Bags', qty: 20, unit: 'MT', rate: 5000, rateUnit: 'Ton', taxable: 100000 }, { hsn: '25221000', product: 'Quick Lime Lumps', qty: 7650, unit: 'Kg', rate: 5300, rateUnit: 'Ton' }], charges: [{ label: 'Freight — Borunda to Haroa', desc: 'By road, full truck load', amount: 12000 }], taxable: 152545, igst: 7627.25, total: 160172.25, grand: 160172.25, words: 'Rupees One Lakh Sixty Thousand One Hundred Seventy Two and Paisa Twenty Five Only' }).replace(/<[^>]+>/g, ' ');
ok('multi-line: both items, the Kg line priced through units-core (40,545.00), the charge as its own row with HSN 9965', /Quick Lime Powder/.test(ml) && /Quick Lime Lumps/.test(ml) && /40,545\.00/.test(ml) && /Freight — Borunda to Haroa/.test(ml) && /9965/.test(ml) && /Charges[\s\S]*12,000\.00/.test(ml));
ok('multi-line: no quantity row in the totals block; the marked total rides under the words line, per unit', !/<td class="l">Total quantity/.test(ml) && /Total quantity:\s+20 MT \+ 7,650 Kg/.test(ml));
ok('no IRN / QR without an IRN', !/IRN|Ack No|e-Invoice QR/.test(t));
const ei = R({ irn: 'abc123def', ackNo: '172621081606743', ackDt: '2026-09-18', qrData: 'signed' });
ok('with a real IRN: IRN, Ack No., Ack Date (dd-mm-yyyy) and the QR', /abc123def/.test(ei) && /172621081606743/.test(ei) && /18-09-2026/.test(ei) && /class="einv ein"/.test(ei));
ok('no export block on a domestic invoice', !/Export Details/.test(t));
const xp = R({ type: 'export', export: { country: 'Nepal', incoterms: 'EXW', currency: 'INR' }, buyer: { name: 'NEW NEPAL ELECTRICALS', address: 'Surkhet, Nepal', gstin: '', state: '' }, igst: 0, gstR: 0 }).replace(/<[^>]+>/g, ' ');
ok('export: EXPORT TAX INVOICE, zero-rated IGST line, Export Details with only the given facts, place of supply Nepal', /EXPORT TAX INVOICE/.test(xp) && /zero-rated export under LUT/.test(xp) && /Export Details/.test(xp) && /Nepal/.test(xp) && /EXW/.test(xp) && !/Shipping Bill/.test(xp) && !/Rajasthan \(08\)[\s\S]*Place of supply/.test(xp.slice(xp.indexOf('Place of supply'))));

/* print: one A4 page for a one-line invoice (Chrome when present) */
(function () {
  const CH = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  if (!fs.existsSync(CH)) { ok('SKIPPED (no Chrome): one-line invoice prints on one page', true); return; }
  const os = require('os'), cp = require('child_process'), tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'prem-'));
  const pages = htmlStr => { const hp = path.join(tmp, 'x.html'), pp = path.join(tmp, 'x.pdf'); fs.writeFileSync(hp, htmlStr); cp.execFileSync(CH, ['--headless=new', '--disable-gpu', '--no-pdf-header-footer', '--print-to-pdf=' + pp, 'file://' + hp], { stdio: 'ignore' }); return (fs.readFileSync(pp, 'latin1').match(/\/Type\s*\/Page[^s]/g) || []).length; };
  ok('a one-line invoice prints on ONE A4 page', pages(R()) === 1);
  ok('a one-line e-invoice with IRN + Ack (no QR) prints on ONE page', pages(R({ irn: 'a'.repeat(64), ackNo: '172621081606743', ackDt: '18-09-2026' })) === 1);
})();

console.log('\n  Passed: ' + pass + '   Failed: ' + fail);
fails.forEach(f => console.log('    ✗ ' + f));
console.log(fail === 0 ? '\n✅ ALL ' + pass + ' PREMIUM TESTS PASSED\n' : '\n❌ ' + fail + ' FAILED\n');
process.exit(fail === 0 ? 0 : 1);
