/* "Deshwali Classic GST Invoice" (id blueink) — the Raj Chemicals & Minerals
   tax e-invoice the owner photographed on 19-09-2026, in Deshwali's name.
   Pins the structure, the hide-empty rules (nothing invented for fields the
   owner has not given), the No. of Bags arithmetic, and a one-page print. */
const fs = require('fs'), path = require('path'), cp = require('child_process');
const T = require('./invoice-templates.js');
let pass = 0, fail = 0; const bad = [];
const ok = (n, c) => { if (c) pass++; else { fail++; bad.push(n); } };
const seller = { name: 'DESHWALI MINERALS', short: 'Deshwali', city: 'Borunda', gstin: '08NLIPS9801K1Z5', address: 'Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan', state: 'Rajasthan (08)', email: 'deshwaliminerals@gmail.com', product: 'Manufacturer & Exporter of Premium Quick Lime and Hydrated Lime', logo: '/v2/deshwali-logo.png', tel: '8875020202, 9460767676', terms: ['Goods once sold will not be taken back or exchanged.', 'Jurisdiction: All disputes shall be subject to the exclusive jurisdiction of courts in Rajasthan, India.'], iec: 'NLIPS9801K', lut: 'AD080826023319U', ownerName: 'Mohammad Salim', msme: 'UDYAM-RJ-25-0061661', msmeType: 'Micro', roundOff: false };
const BASE = { seller, hsn: '25221000', buyer: { name: 'RASHMI GREEN HYDROGEN STEEL PRIVATE LIMITED', gstin: '19AALCR1619N1ZT', address: 'Khatranga, Changual, Gopinathpur, Kharagpur, Paschim Medinipur, West Bengal 721301', state: 'West Bengal (19)' }, pos: 'West Bengal (19)', inv: '9/2026-27', date: '2026-09-19', po: '4100004169', poDate: '2026-08-19', product: 'Burnt (Calcined) Lime Powder 0-3 mm', packing: '50 kg HDPE bags', qty: 40.96, rate: 5250, unit: 'Ton', rateUnit: 'Ton', gstR: 5, transport: 'By Road', veh: 'RJ01GE5906', station: 'Kharagpur', grrr: '', eway: '751666395846', taxable: 215040, cgst: 5376, sgst: 5376, igst: 10752, interState: true, total: 225792, roundOff: 0, grand: 225792, words: 'Rupees Two Lakh Twenty Five Thousand Seven Hundred Ninety Two Only' };
const R = (o) => T.render(Object.assign({}, BASE, o || {}), { template: 'blueink' });
const txt = (h) => h.replace(/<style>[\s\S]*?<\/style>/g, '').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&ndash;/g, '–').replace(/&amp;/g, '&').replace(/\s+/g, ' ');
const h = R(), t = txt(h);

console.log('\n═══ Deshwali Classic GST Invoice (blueink) ═══');
const reg = T.TEMPLATES.find(x => x.id === 'blueink');
ok('registered last: "Deshwali Classic GST Invoice", accentable (the ink colour), despatch:true, and never under the retired id "classic"', reg && reg.name === 'Deshwali Classic GST Invoice' && reg.accentable === true && reg.despatch === true && T.TEMPLATES[T.TEMPLATES.length - 1].id === 'blueink' && !T.TEMPLATES.some(x => x.id === 'classic'));
ok('blue ink throughout: the body colour and every rule are the accent (default #24479A); Arial-type body, serif firm name', /body\{font-family:Arial[^}]*color:#24479A/.test(h) && /\.inv\{border:1px solid #24479A/.test(h) && /font-family:Arial,Helvetica/.test(h) && /\.cn\{font-family:Georgia/.test(h) && /body\{font-family:Arial[^}]*color:#0B3D91/.test(T.render(BASE, { template: 'blueink', accent: '#0B3D91' })));
ok('letterhead: GSTIN / PAN / IEC top-left, logo + name + tagline centred, +91 phones and e-mail top-right, ORIGINAL COPY, underlined TAX INVOICE', /<b>GSTIN<\/b>: 08NLIPS9801K1Z5/.test(h) && /<b>PAN<\/b>: NLIPS9801K/.test(h) && /<b>IEC<\/b>: NLIPS9801K/.test(h) && /class="cn">DESHWALI MINERALS</.test(h) && /class="tg">Manufacturer &amp; Exporter of Premium Quick Lime and Hydrated Lime</.test(h) && /\+91 8875020202, \+91 9460767676/.test(t) && /deshwaliminerals@gmail\.com/.test(t) && /ORIGINAL COPY/.test(t) && /class="ttl bb"><span>TAX INVOICE</.test(h) && /<img src="\/v2\/deshwali-logo\.png"[^>]*alt=/.test(h));
ok('no CIN line for a proprietorship (none on the profile) — nothing invented', !/CIN/.test(t));
ok('left box: MSME No. UDYAM-RJ-25-0061661 (the certificate of 27-12-2023), MSME Type Micro, Invoice No, Invoice Date dd-mm-yyyy, Eway Bill No.', /MSME No\. : UDYAM-RJ-25-0061661/.test(t) && /MSME Type : Micro/.test(t) && /Invoice No : 9\/2026-27/.test(t) && /Invoice Date : 19-09-2026/.test(t) && /Eway Bill No\. : 751666395846/.test(t));
ok('right box: PO No. with its Date, Transport Mode, GR/RR No., From (the kiln), Station, Place of Supply, Vehicle No.', /PO No\. : 4100004169 Date : 19-08-2026/.test(t) && /Transport Mode : By Road/.test(t) && /GR\/RR No\. :/.test(t) && /From : Borunda/.test(t) && /Station : Kharagpur/.test(t) && /Place of Supply : West Bengal \(19\)/.test(t) && /Vehicle No\. : RJ01GE5906/.test(t));
ok('a firm without an MSME number prints no MSME lines; a sale without a PO prints no PO line; Documents through only when the firm gives it', !/MSME/.test(txt(R({ seller: Object.assign({}, seller, { msme: '', msmeType: '' }) }))) && !/PO No\./.test(txt(R({ po: '' }))) && !/DOCUMENTS THROUGH/.test(t) && /DOCUMENTS THROUGH : HDFC Bank, Merta/.test(txt(R({ seller: Object.assign({}, seller, { docsThrough: 'HDFC Bank, Merta' }) }))));
ok('Buyer (Billed to) and Consignee (Shipped to) boxes: Name, Address, State, PAN No (off the GSTIN), GSTIN — consignee = buyer unless the sale names one', (t.match(/RASHMI GREEN HYDROGEN STEEL PRIVATE LIMITED/g) || []).length === 2 && /PAN No : AALCR1619N/.test(t) && /Details of Consignee \(Shipped to\)/.test(t) && /Name : SOME SITE/.test(txt(R({ consignee: { name: 'SOME SITE', address: 'Plot 9', state: 'Odisha (21)', gstin: '' } }))));
ok('goods table: S.No · HSN CODE · DESCRIPTION OF GOODS · NO. OF BAGS · QTY (Ton) · RATE (P.Ton) · AMOUNT, description upper-cased by CSS (the text stays as entered), logo watermarked behind', /S\.No\. HSN CODE DESCRIPTION OF GOODS NO\. OF BAGS QTY \(Ton\) RATE \(P\.Ton\) AMOUNT/.test(t) && /class="dn">Burnt \(Calcined\) Lime Powder 0-3 mm</.test(h) && /\.it \.dn\{font-weight:700;text-transform:uppercase\}/.test(h) && /class="wm"><img/.test(h));
ok('No. of Bags: 40.96 Ton in 50 kg bags = 819; no bags column when the packing says nothing', /<td class="c">819<\/td>/.test(h) && !/NO\. OF BAGS/.test(txt(R({ packing: '' }))) && /<td class="c">30<\/td>/.test(R({ items: [{ hsn: '25221000', product: 'Lime', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, bags: 30 }] })));
ok('the line: 40.96 · 5,250.00 · 2,15,040.00; Packing and Forwarding Charges 0.00 (the row prints either way, as the sample does); Total Taxable Value with the quantity total marked', /40\.96 5,250\.00 2,15,040\.00/.test(t) && /Packing and Forwarding Charges 0\.00/.test(t) && /Total Taxable Value \(\s*40\.96 Ton\s*\) 2,15,040\.00/.test(t) && /class="qtytot[^"]*">40\.96 Ton</.test(h) && /Packing and Forwarding Charges 1,500\.00/.test(txt(R({ packingCharge: 1500 }))));
ok('the sample\'s two lines: goods + a transportation charge as line 2 with its own HSN, no bags / qty / rate for the charge', (function () { const x = txt(R({ items: [{ hsn: '25221000', product: 'Burnt (Calcined) Lime Powder 0-3 mm', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, packing: '50 kg HDPE bags' }], charges: [{ label: 'Transportation charges upto Kharagpur', amount: 137216, hsn: '25221000' }], taxable: 352256 })); return /2\. 25221000 Transportation charges upto Kharagpur – – – 1,37,216\.00/.test(x); })());
ok('tax stack (inter-state): ADD: CGST – · ADD: SGST – · ADD: IGST @ 5.00 % 10,752.00 · GST Tax Amount · Amount After Tax · Total Amount · GST Reverse Charge N.A.', /ADD: CGST – ADD: SGST – ADD: IGST @ 5\.00 % 10,752\.00 GST Tax Amount 10,752\.00 Amount After Tax 2,25,792\.00 Total Amount 2,25,792\.00 GST Reverse Charge N\.A\./.test(t));
ok('intra-state: CGST @ 2.50 % and SGST @ 2.50 % carry the figures, IGST is a dash; reverse charge says Yes when it applies; TCS and Round Off rows only when non-zero', (function () { const x = txt(R({ interState: false, igst: 0, rcm: true })); return /ADD: CGST @ 2\.50 % 5,376\.00 ADD: SGST @ 2\.50 % 5,376\.00 ADD: IGST –/.test(x) && /GST Reverse Charge Yes/.test(x) && !/TCS/.test(t) && !/Round Off/.test(t) && /ADD : TCS 2,258\.00/.test(txt(R({ tcs: 2258 }))) && /Round Off \+0\.20/.test(txt(R({ total: 369868.8, grand: 369869 }))); })());
ok('Remarks line, the HSN-wise tax summary on the left, no LUT line on a domestic sale; an export prints LUT Bond No. and the LUT declaration', /Remarks :/.test(t) && /HSN\/SAC Rate Taxable IGST Amt\. Total tax 25221000 5\.00%/.test(t) && !/LUT Bond/.test(t) && (function () { const x = txt(R({ type: 'export', export: { country: 'Nepal' } })); return /LUT Bond No\. : AD080826023319U/.test(x) && /export under LUT without payment of IGST/.test(x) && /Place of Supply : Nepal/.test(x); })());
ok('e-invoice: TAX E-INVOICE title, IRN / AckNo / AckDt and the QR only when the sale carries them', !/IRN/.test(t) && (function () { const x = R({ irn: '818d875e443e3c8d340ad284d9eb3d35de8478812a5d34fa107f701f26dad006', ackNo: '172621081606743', ackDt: '02-09-2026 22:49:00', qrData: 'x' }); return /class="ttl bb"><span>TAX E-INVOICE</.test(x) && /<b>IRN:<\/b> 818d875e/.test(x) && /<b>AckNo:<\/b> 172621081606743/.test(x) && /alt="e-invoice QR"/.test(x); })());
ok('AMOUNT IN WORDS, the firm\'s own terms as bullets (no E.&O.E.), For: DESHWALI MINERALS · MOHAMMAD SALIM · Authorised Signatory, REGD. ADDRESS footer, no UNIT ADDRESS until the owner gives one', /AMOUNT IN WORDS: Rupees Two Lakh Twenty Five Thousand Seven Hundred Ninety Two Only/.test(t) && /<li>Goods once sold will not be taken back or exchanged\.<\/li>/.test(h) && !/O\.E\./.test(t) && /For: DESHWALI MINERALS/.test(t) && /class="nm">MOHAMMAD SALIM</.test(h) && /Authorised Signatory/.test(t) && /REGD\. ADDRESS : Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan/.test(t) && !/UNIT ADDRESS/.test(t) && /UNIT ADDRESS : Khasra 12, Gotan/.test(txt(R({ seller: Object.assign({}, seller, { unitAddress: 'Khasra 12, Gotan' }) }))));
ok('print rules: A4 with no browser margin (no header/footer strings), the sheet fills the page (flex column) so the goods table stretches and the footer sits at the foot', /@page\{size:A4;margin:0\}/.test(h) && /@media print\{\.sheet\{[^}]*min-height:100vh;display:flex;flex-direction:column\}/.test(h) && /\.body\{position:relative;flex:1/.test(h) && !/document\.title/.test(h));

/* one page, in the browser's own print engine */
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
if (fs.existsSync(chrome)) {
  const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'blueink-'));
  const cases = { one: h, two: R({ items: [{ hsn: '25221000', product: 'Burnt (Calcined) Lime Powder 0-3 mm', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, packing: '50 kg HDPE bags' }], charges: [{ label: 'Transportation charges upto Kharagpur', amount: 137216, hsn: '25221000' }], irn: '818d875e443e3c8d340ad284d9eb3d35de8478812a5d34fa107f701f26dad006', ackNo: '172621081606743', ackDt: '02-09-2026 22:49:00' }), four: R({ items: [1, 2, 3, 4].map(i => ({ hsn: '25221000', product: 'Quick Lime lot ' + i, qty: 10, unit: 'Ton', rate: 5000, rateUnit: 'Ton', taxable: 50000 })) }) };
  Object.keys(cases).forEach(k => {
    const f = path.join(tmp, k + '.html'); fs.writeFileSync(f, cases[k].replace(/src="\/v2\/deshwali-logo\.png"/g, 'src=""'));
    try { cp.execFileSync(chrome, ['--headless=new', '--disable-gpu', '--no-sandbox', '--print-to-pdf=' + path.join(tmp, k + '.pdf'), 'file://' + f], { stdio: 'ignore', timeout: 60000 }); } catch (e) {}
    const pdf = fs.existsSync(path.join(tmp, k + '.pdf')) ? fs.readFileSync(path.join(tmp, k + '.pdf'), 'latin1') : '';
    const pages = Math.max.apply(null, (pdf.match(/\/Count (\d+)/g) || ['/Count 0']).map(x => +x.slice(7)));
    ok('prints on exactly one A4 page (' + k + ' line case)', pages === 1);
  });
} else console.log('  (Chrome not found — page-count checks skipped)');

console.log('\n  Passed: ' + pass + '   Failed: ' + fail); bad.forEach(n => console.log('    ✗ ' + n));
console.log(fail ? '\n❌ ' + fail + ' FAILED' : '\n✅ ALL ' + pass + ' BLUEINK TESTS PASSED');
process.exit(fail ? 1 : 0);
