/* "Deshwali Classic GST Invoice" (id blueink) — the Raj Chemicals & Minerals
   tax e-invoice the owner photographed on 19-09-2026, in Deshwali's name.
   Pins the structure, the hide-empty rules (nothing invented for fields the
   owner has not given), the No. of Bags arithmetic, and a one-page print. */
const fs = require('fs'), path = require('path'), cp = require('child_process');
const T = require('./invoice-templates.js');
let pass = 0, fail = 0; const bad = [];
const ok = (n, c) => { if (c) pass++; else { fail++; bad.push(n); } };
const seller = { name: 'DESHWALI MINERALS', short: 'Deshwali', city: 'Borunda', gstin: '08NLIPS9801K1Z5', lockupDark: '/v2/deshwali-lockup-dark.svg?v=1', sealText: 'BORUNDA, GOTAN', website: 'www.deshwaliminerals.com', slogan: 'Quality Lime for a Stronger Tomorrow', address: 'Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan', state: 'Rajasthan (08)', email: 'deshwaliminerals@gmail.com', product: 'Manufacturer & Exporter of Premium Quick Lime and Hydrated Lime', logo: '/v2/deshwali-logo.png', tel: '8875020202, 9460767676', terms: ['Goods once sold will not be taken back or exchanged.', 'Jurisdiction: All disputes shall be subject to the exclusive jurisdiction of courts in Rajasthan, India.'], iec: 'NLIPS9801K', lut: 'AD080826023319U', ownerName: 'Mohammad Salim', msme: 'UDYAM-RJ-25-0061661', msmeType: 'Micro', roundOff: false };
const BASE = { seller, hsn: '25221000', buyer: { name: 'RASHMI GREEN HYDROGEN STEEL PRIVATE LIMITED', gstin: '19AALCR1619N1ZT', address: 'Khatranga, Changual, Gopinathpur, Kharagpur, Paschim Medinipur, West Bengal 721301', state: 'West Bengal (19)' }, pos: 'West Bengal (19)', inv: '9/2026-27', date: '2026-09-19', po: '4100004169', poDate: '2026-08-19', product: 'Burnt (Calcined) Lime Powder 0-3 mm', packing: '50 kg HDPE bags', qty: 40.96, rate: 5250, unit: 'Ton', rateUnit: 'Ton', gstR: 5, transport: 'By Road', veh: 'RJ01GE5906', station: 'Kharagpur', grrr: '', eway: '751666395846', taxable: 215040, cgst: 5376, sgst: 5376, igst: 10752, interState: true, total: 225792, roundOff: 0, grand: 225792, words: 'Rupees Two Lakh Twenty Five Thousand Seven Hundred Ninety Two Only' };
const R = (o) => T.render(Object.assign({}, BASE, o || {}), { template: 'blueink' });
const txt = (h) => h.replace(/<style>[\s\S]*?<\/style>/g, '').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&ndash;/g, '–').replace(/&amp;/g, '&').replace(/\s+/g, ' ');
const h = R(), t = txt(h);

console.log('\n═══ Deshwali Classic GST Invoice (blueink) — the owner\'s quotation mock, as a tax invoice ═══');
const reg = T.TEMPLATES.find(x => x.id === 'blueink');
const JWS = 'eyJhbGciOiJSUzI1NiJ9.' + 'eyJkYXRhIjoiUXVpY2tMaW1lIn0'.repeat(10) + '.c2ln';
ok('registered last: "Deshwali Classic GST Invoice", accentable (the brand blue), despatch:true, never under the retired id "classic"', reg && reg.name === 'Deshwali Classic GST Invoice' && reg.accentable === true && reg.despatch === true && T.TEMPLATES[T.TEMPLATES.length - 1].id === 'blueink' && !T.TEMPLATES.some(x => x.id === 'classic'));
ok('brand blue #1B5FA8 for the band, the table header and the Grand Total; navy text; a picked accent replaces the blue', /\.band\{background:#1B5FA8/.test(h) && /\.it th\{background:#1B5FA8;color:#fff/.test(h) && /\.tx tr\.gt td\{background:#1B5FA8/.test(h) && /body\{font-family:'Segoe UI'[^}]*color:#0E2A47/.test(h) && /\.band\{background:#0B3D91/.test(T.render(BASE, { template: 'blueink', accent: '#0B3D91' })));
ok('letterhead: the BRAND LOCKUP (Dark.svg — never a re-typeset name) with the product line under it; the contact block with pin / phone / mail / globe icons: address + ", India", +91 phones, e-mail, website', /<img class="lk" src="\/v2\/deshwali-lockup-dark\.svg\?v=1" alt="DESHWALI MINERALS">/.test(h) && !/class="nm">DESHWALI/.test(h.slice(0, h.indexOf('class="band"'))) && /class="tg">Manufacturer &amp; Exporter of Premium Quick Lime and Hydrated Lime</.test(h) && (h.match(/<svg viewBox="0 0 24 24">/g) || []).length === 4 && /Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan, India/.test(t) && /\+91 8875020202, \+91 9460767676/.test(t) && /deshwaliminerals@gmail\.com/.test(t) && /www\.deshwaliminerals\.com/.test(t));
ok('a firm without a lockup gets its logo beside its name; without a website the globe line and the foot band are absent', (function () { const x = R({ seller: Object.assign({}, seller, { lockupDark: '', website: '' }) }); return /class="nm">DESHWALI MINERALS</.test(x) && /<img src="\/v2\/deshwali-logo\.png"/.test(x) && !/class="site"/.test(x) && (x.match(/<svg viewBox="0 0 24 24">/g) || []).length === 3; })());
ok('the title band: TAX INVOICE · the firm\'s slogan · ORIGINAL COPY; no slogan line for a firm without one; TAX E-INVOICE once an IRN exists; EXPORT INVOICE for an export', /class="band"><div class="t"><div class="w">TAX INVOICE<\/div><div class="sl">Quality Lime for a Stronger Tomorrow<\/div><\/div><div class="c">ORIGINAL COPY</.test(h) && !/class="sl"/.test(R({ seller: Object.assign({}, seller, { slogan: '' }) })) && /class="w">TAX E-INVOICE</.test(R({ irn: 'a'.repeat(64), signedQr: JWS })) && /class="w">EXPORT INVOICE</.test(R({ type: 'export', export: { country: 'Nepal' } })));
ok('two strips of four boxes with blue labels: Invoice No. · Invoice Date dd-mm-yyyy · E-Way Bill No. · Reference / PO (with its date); Transport · Vehicle No. · Station · GR/RR No. — "--" for an empty value like the mock', /Invoice No\. 9\/2026-27 Invoice Date 19-09-2026 E-Way Bill No\. 751666395846 Reference \/ PO 4100004169 · 19-08-2026/.test(t) && /Transport By Road Vehicle No\. RJ01GE5906 Station Kharagpur GR\/RR No\. --/.test(t) && /\.strip span\{[^}]*color:#1B5FA8/.test(h) && /Reference \/ PO --/.test(txt(R({ po: '' }))));
ok('BILL TO / SHIP TO: the name bold, the address, then GSTIN · PAN (off the GSTIN) · STATE · CONTACT with aligned colons; Ship To = Bill To unless the sale names a consignee', (t.match(/RASHMI GREEN HYDROGEN STEEL PRIVATE LIMITED/g) || []).length === 2 && /GSTIN : 19AALCR1619N1ZT PAN : AALCR1619N STATE : West Bengal \(19\) CONTACT : --/.test(t) && /\.kv \.k\{width:64px/.test(h) && /Ship To SOME SITE/.test(txt(R({ consignee: { name: 'SOME SITE', address: 'Plot 9', state: 'Odisha (21)', gstin: '' } }))) && /CONTACT : Mr\. Aroof/.test(txt(R({ buyer: Object.assign({}, BASE.buyer, { contact: 'Mr. Aroof' }) }))));
ok('goods table with a blue header — S.No. · HSN Code · Description of Goods · Unit · Qty · Rate (₹) · Amount (₹); the description upper-cased by CSS with its sub-line; the diamond watermarked behind', /S\.No\. HSN Code Description of Goods Unit Qty Rate \(₹\) Amount \(₹\)/.test(t) && /class="dn">Burnt \(Calcined\) Lime Powder 0-3 mm</.test(h) && /\.it \.dn\{font-weight:800;color:#0E2A47;text-transform:uppercase\}/.test(h) && /class="ds">High quality/.test(R({ items: [{ hsn: '25221000', product: 'Lime', desc: 'High quality Quick Lime (CaO)', qty: 30, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 157500 }] })) && /class="wm"><img/.test(h));
ok('the line: Ton · 40.96 · 5,250.00 · 2,15,040.00; a Kg line priced per Ton says so in the header', /1 25221000 Burnt \(Calcined\) Lime Powder 0-3 mm Ton 40\.96 5,250\.00 2,15,040\.00/.test(t) && /Rate \(₹\)<br>per Ton/.test(R({ unit: 'Kg', qty: 7650, rateUnit: 'Ton', rate: 5300 })));
ok('the mock\'s two lines: goods + a transportation charge as line 2 with its own HSN, dashes for unit / qty / rate', /2 25221000 Transportation charges upto Kharagpur – – – 1,37,216\.00/.test(txt(R({ items: [{ hsn: '25221000', product: 'Burnt (Calcined) Lime Powder 0-3 mm', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040 }], charges: [{ label: 'Transportation charges upto Kharagpur', amount: 137216, hsn: '25221000' }], taxable: 352256 }))));
ok('below the table: Total Quantity (the marked quantity total) and Amount in Words on the left, the totals stack on the right ending in a blue Grand Total cell', /Total Quantity 40\.96 Ton Amount in Words : Rupees Two Lakh Twenty Five Thousand Seven Hundred Ninety Two Only Total \(₹\) 2,15,040\.00 Add: IGST @ 5\.00% 10,752\.00 Total Tax Amount 10,752\.00 Grand Total \(₹\) 2,25,792\.00/.test(t) && /class="qtytot[^"]*">40\.96 Ton</.test(h) && /<tr class="gt"><td>Grand Total/.test(h));
ok('intra-state shows Add: CGST @ 2.50% and Add: SGST @ 2.50%; TCS and Round Off only when non-zero; an export says zero-rated under LUT', /Add: CGST @ 2\.50% 5,376\.00 Add: SGST @ 2\.50% 5,376\.00/.test(txt(R({ interState: false, igst: 0 }))) && !/TCS|Round Off/.test(t) && /Add: TCS 2,258\.00/.test(txt(R({ tcs: 2258 }))) && /Round Off \+0\.20/.test(txt(R({ total: 369868.8, grand: 369869 }))) && /IGST — zero-rated export under LUT/.test(txt(R({ type: 'export' }))));
ok('the e-invoice block sits under the totals when an IRN exists: IRN · Ack No. · Ack Date · the signed QR · "Scan to verify e-Invoice"; nothing at all without an IRN', !/IRN|qrimg/.test(t.replace(/<style>[\s\S]*?<\/style>/, '')) && (function () { const x = R({ irn: 'a'.repeat(64), ackNo: '172621081606743', ackDt: '2026-09-02 22:49:00', signedQr: JWS }); return /<span>IRN<\/span><b>aaaa/.test(x) && /<span>Ack No\.<\/span><b>172621081606743/.test(x) && /<span>Ack Date<\/span><b>02-09-2026 22:49:00/.test(x) && /<svg class="qrimg"/.test(x) && /Scan to verify e-Invoice/.test(x) && x.indexOf('class="einv ein"') > x.indexOf('class="tots"'); })());
ok('terms numbered 1..n against For DESHWALI MINERALS · a signature space · Authorised Signatory — no name, no seal, no "Signature valid"', /<ol><li>Goods once sold will not be taken back or exchanged\.<\/li>/.test(h) && /For DESHWALI MINERALS/.test(t) && /class="sp"><\/div><div class="as">Authorised Signatory</.test(h) && !/MOHAMMAD SALIM|Signature valid|<svg class="seal"/.test(h));
ok('the foot: GSTIN | PAN | MSME, the plant address (the unit address when the firm has one, else the registered one) with the product line, then the blue website band', /GSTIN : 08NLIPS9801K1Z5 \| PAN : NLIPS9801K \| MSME : UDYAM-RJ-25-0061661/.test(t) && /Plant Address : Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan Manufacturer & Exporter of Premium Quick Lime and Hydrated Lime/.test(t) && /class="site">www\.deshwaliminerals\.com</.test(h) && /Plant Address : Khasra 12, Gotan/.test(txt(R({ seller: Object.assign({}, seller, { unitAddress: 'Khasra 12, Gotan' }) }))));
ok('print rules: A4 with no browser margin; the sheet is a flex column that fills the page so the foot band sits at the bottom; the narrow app preview zooms the fixed 820px sheet', /@page\{size:A4;margin:0\}/.test(h) && /@media print\{\.sheet\{width:auto;padding:8mm 9mm 0;min-height:100vh\}\}/.test(h) && /\.sheet\{width:820px[^}]*display:flex;flex-direction:column;min-height:1130px\}/.test(h) && /@media screen and \(max-width:900px\)\{body\{overflow-x:hidden\}\.sheet\{zoom:\.72\}\}/.test(h));

/* one page, in the browser's own print engine */
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
if (fs.existsSync(chrome)) {
  const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'blueink-'));
  const cases = { one: h, two: R({ items: [{ hsn: '25221000', product: 'Burnt (Calcined) Lime Powder 0-3 mm', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, packing: '50 kg HDPE bags' }], charges: [{ label: 'Transportation charges upto Kharagpur', amount: 137216, hsn: '25221000' }], irn: '818d875e443e3c8d340ad284d9eb3d35de8478812a5d34fa107f701f26dad006', ackNo: '172621081606743', ackDt: '02-09-2026 22:49:00' }), four: R({ items: [1, 2, 3, 4].map(i => ({ hsn: '25221000', product: 'Quick Lime lot ' + i, qty: 10, unit: 'Ton', rate: 5000, rateUnit: 'Ton', taxable: 50000 })) }) };
  Object.keys(cases).forEach(k => {
    const f = path.join(tmp, k + '.html'); fs.writeFileSync(f, cases[k].replace(/src="\/v2\/deshwali-logo\.png"/g, 'src=""').replace(/src="\/v2\/deshwali-lockup-dark\.svg\?v=1"/g, 'src="file://' + __dirname + '/deshwali-lockup-dark.svg"'));
    try { cp.execFileSync(chrome, ['--headless=new', '--disable-gpu', '--no-sandbox', '--print-to-pdf=' + path.join(tmp, k + '.pdf'), 'file://' + f], { stdio: 'ignore', timeout: 60000 }); } catch (e) {}
    const pdf = fs.existsSync(path.join(tmp, k + '.pdf')) ? fs.readFileSync(path.join(tmp, k + '.pdf'), 'latin1') : '';
    const pages = Math.max.apply(null, (pdf.match(/\/Count (\d+)/g) || ['/Count 0']).map(x => +x.slice(7)));
    ok('prints on exactly one A4 page (' + k + ' line case)', pages === 1);
  });
} else console.log('  (Chrome not found — page-count checks skipped)');

console.log('\n  Passed: ' + pass + '   Failed: ' + fail); bad.forEach(n => console.log('    ✗ ' + n));
console.log(fail ? '\n❌ ' + fail + ' FAILED' : '\n✅ ALL ' + pass + ' BLUEINK TESTS PASSED');
process.exit(fail ? 1 : 0);
