/* "Deshwali Classic GST Invoice" (id blueink) — the Raj Chemicals & Minerals
   tax e-invoice the owner photographed on 19-09-2026, in Deshwali's name.
   Pins the structure, the hide-empty rules (nothing invented for fields the
   owner has not given), the No. of Bags arithmetic, and a one-page print. */
const fs = require('fs'), path = require('path'), cp = require('child_process');
const T = require('./invoice-templates.js');
let pass = 0, fail = 0; const bad = [];
const ok = (n, c) => { if (c) pass++; else { fail++; bad.push(n); } };
const seller = { name: 'DESHWALI MINERALS', short: 'Deshwali', city: 'Borunda', gstin: '08NLIPS9801K1Z5', lockupDark: '/v2/deshwali-lockup-dark.svg?v=1', sealText: 'BORUNDA, GOTAN', address: 'Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan', state: 'Rajasthan (08)', email: 'deshwaliminerals@gmail.com', product: 'Manufacturer & Exporter of Premium Quick Lime and Hydrated Lime', logo: '/v2/deshwali-logo.png', tel: '8875020202, 9460767676', terms: ['Goods once sold will not be taken back or exchanged.', 'Jurisdiction: All disputes shall be subject to the exclusive jurisdiction of courts in Rajasthan, India.'], iec: 'NLIPS9801K', lut: 'AD080826023319U', ownerName: 'Mohammad Salim', msme: 'UDYAM-RJ-25-0061661', msmeType: 'Micro', roundOff: false };
const BASE = { seller, hsn: '25221000', buyer: { name: 'RASHMI GREEN HYDROGEN STEEL PRIVATE LIMITED', gstin: '19AALCR1619N1ZT', address: 'Khatranga, Changual, Gopinathpur, Kharagpur, Paschim Medinipur, West Bengal 721301', state: 'West Bengal (19)' }, pos: 'West Bengal (19)', inv: '9/2026-27', date: '2026-09-19', po: '4100004169', poDate: '2026-08-19', product: 'Burnt (Calcined) Lime Powder 0-3 mm', packing: '50 kg HDPE bags', qty: 40.96, rate: 5250, unit: 'Ton', rateUnit: 'Ton', gstR: 5, transport: 'By Road', veh: 'RJ01GE5906', station: 'Kharagpur', grrr: '', eway: '751666395846', taxable: 215040, cgst: 5376, sgst: 5376, igst: 10752, interState: true, total: 225792, roundOff: 0, grand: 225792, words: 'Rupees Two Lakh Twenty Five Thousand Seven Hundred Ninety Two Only' };
const R = (o) => T.render(Object.assign({}, BASE, o || {}), { template: 'blueink' });
const txt = (h) => h.replace(/<style>[\s\S]*?<\/style>/g, '').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&ndash;/g, '–').replace(/&amp;/g, '&').replace(/\s+/g, ' ');
const h = R(), t = txt(h);

console.log('\n═══ Deshwali Classic GST Invoice (blueink) ═══');
const reg = T.TEMPLATES.find(x => x.id === 'blueink');
ok('registered last: "Deshwali Classic GST Invoice", accentable (the ink colour), despatch:true, and never under the retired id "classic"', reg && reg.name === 'Deshwali Classic GST Invoice' && reg.accentable === true && reg.despatch === true && T.TEMPLATES[T.TEMPLATES.length - 1].id === 'blueink' && !T.TEMPLATES.some(x => x.id === 'classic'));
ok('the firm\'s own modern language (his words on the first cut: "no alignment or modern design"): navy ink #013E5B off the lockup, grey rules, Arial body — never a redrawn serif name', /body\{font-family:Arial[^}]*color:#1a1a1a/.test(h) && /border-bottom:2px solid #013E5B/.test(h) && !/Georgia/.test(h) && /\.it th\{background:#013E5B;color:#fff/.test(h) && /border-bottom:2px solid #0B3D91/.test(T.render(BASE, { template: 'blueink', accent: '#0B3D91' })));
ok('letterhead: the BRAND LOCKUP (the navy Dark.svg the owner gave — the firm name is never re-typeset next to it), the tagline under it, TAX INVOICE + Original Copy on the right', /<img class="lk" src="\/v2\/deshwali-lockup-dark\.svg\?v=1" alt="DESHWALI MINERALS">/.test(h) && !/class="nm">DESHWALI/.test(h.slice(0, h.indexOf('class="reg"'))) && /class="tg">Manufacturer &amp; Exporter of Premium Quick Lime and Hydrated Lime</.test(h) && /class="w">TAX INVOICE</.test(h) && /Original Copy/.test(t));
ok('a firm without a lockup gets its logo beside its name (no lockup → nothing invented, the name typeset)', (function () { const x = R({ seller: Object.assign({}, seller, { lockupDark: '' }) }); return /class="nm">DESHWALI MINERALS</.test(x) && /<img src="\/v2\/deshwali-logo\.png"/.test(x); })());
ok('letterhead like the reference: GSTIN / PAN / IEC stacked left (no CIN for a proprietorship), the lockup + tagline centred, +91 phones · e-mail · website stacked right', /class="ids"><b>GSTIN<\/b>: 08NLIPS9801K1Z5<br><b>PAN<\/b>: NLIPS9801K<br><b>IEC<\/b>: NLIPS9801K<\/div>/.test(h) && !/CIN/.test(t) && /class="ctc">\+91 8875020202<br>\+91 9460767676<br>deshwaliminerals@gmail\.com/.test(h) && /class="mid"><img class="lk"/.test(h) && /class="ttl"><div class="w">TAX INVOICE<\/div><div class="c">Original Copy</.test(h));
ok('left box in the reference\'s order: MSME No UDYAM-RJ-25-0061661 · MSME Type Micro · Invoice No · Invoice Date dd-mm-yyyy · E-Way Bill No; right box: PO No + Date · Transport Mode · GR/RR No. · From with Place of Supply on the same line · Station · Vehicle No', /MSME No : UDYAM-RJ-25-0061661 MSME Type : Micro Invoice No : 9\/2026-27 Invoice Date : 19-09-2026 E-Way Bill No : 751666395846/.test(t) && /PO No : 4100004169 Date 19-08-2026 Transport Mode : By Road GR\/RR No\. : From : Borunda Place of Supply West Bengal \(19\) Station : Kharagpur Vehicle No : RJ01GE5906/.test(t) && !/MSME/.test(txt(R({ seller: Object.assign({}, seller, { msme: '', msmeType: '' }) }))));
ok('one grid for every block: the label column is 110px with a colon column, values bold; party boxes on the same grid with a 64px label', /\.kv \.k\{width:110px/.test(h) && /\.pc \.kv \.k\{width:64px\}/.test(h) && /\.grid2\{display:grid;grid-template-columns:1fr 1fr/.test(h));
ok('a sale without a PO prints no PO line; Documents through prints the firm itself unless the profile names another (the reference\'s own line)', !/PO No/.test(txt(R({ po: '' }))) && /Documents through DESHWALI MINERALS/.test(t) && /Documents through HDFC Bank, Merta/.test(txt(R({ seller: Object.assign({}, seller, { docsThrough: 'HDFC Bank, Merta' }) }))));
ok('Buyer (Billed to) and Consignee (Shipped to): Name, Address, State, PAN No (off the GSTIN), GSTIN — consignee = buyer unless the sale names one', (t.match(/RASHMI GREEN HYDROGEN STEEL PRIVATE LIMITED/g) || []).length === 2 && /PAN No : AALCR1619N/.test(t) && /DETAILS OF CONSIGNEE \(SHIPPED TO\)|Details of Consignee \(Shipped to\)/.test(t) && /Name : SOME SITE/.test(txt(R({ consignee: { name: 'SOME SITE', address: 'Plot 9', state: 'Odisha (21)', gstin: '' } }))));
ok('goods table: navy header — S.No. · HSN Code · Description of Goods · No. of Bags · Qty (Ton) · Rate (P.Ton) · Amount; description as entered; the logo watermarked behind', /S\.No\. HSN Code Description of Goods No\. of Bags Qty \(Ton\) Rate \(P\.Ton\) Amount/.test(t) && /class="dn">Burnt \(Calcined\) Lime Powder 0-3 mm</.test(h) && /class="wm"><img/.test(h));
ok('No. of Bags is always a column like the reference: 40.96 Ton in 50 kg bags = 819; a dash when the packing says nothing; a line\'s own count wins', /<td class="c">819<\/td>/.test(h) && /No\. of Bags/.test(txt(R({ packing: '' }))) && /<td class="c">&ndash;<\/td>/.test(R({ packing: '' })) && /<td class="c">30<\/td>/.test(R({ items: [{ hsn: '25221000', product: 'Lime', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, bags: 30 }] })));
ok('the line: 40.96 · 5,250.00 · 2,15,040.00; Packing and Forwarding Charges 0.00 (the row prints either way, as the sample does); Total Taxable Value with the quantity total marked', /40\.96 5,250\.00 2,15,040\.00/.test(t) && /Packing and Forwarding Charges 0\.00/.test(t) && /Total Taxable Value \(\s*40\.96 Ton\s*\) 2,15,040\.00/.test(t) && /class="qtytot[^"]*">40\.96 Ton</.test(h) && /Packing and Forwarding Charges 1,500\.00/.test(txt(R({ packingCharge: 1500 }))));
ok('the sample\'s two lines: goods + a transportation charge as line 2 with its own HSN, no bags / qty / rate for the charge', /2 25221000 Transportation charges upto Kharagpur – – – 1,37,216\.00/.test(txt(R({ items: [{ hsn: '25221000', product: 'Burnt (Calcined) Lime Powder 0-3 mm', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, packing: '50 kg HDPE bags' }], charges: [{ label: 'Transportation charges upto Kharagpur', amount: 137216, hsn: '25221000' }], taxable: 352256 }))));
ok('the goods area is compact (owner: "too much spacing"): rows at their natural height, a fixed 96px filler with the watermark, then the two summary rows — the page follows the content', /\.body \.fill\{height:96px/.test(h) && /class="fill"><\/div><table class="sum">/.test(h) && !/min-height:1160px/.test(h) && !/class="sp"/.test(h));
ok('tax stack (inter-state): CGST – · SGST – · IGST @ 5.00 % 10,752.00 · GST Tax Amount · Amount After Tax · Total Amount · GST Reverse Charge N.A.', /CGST – SGST – IGST @ 5\.00 % 10,752\.00 GST Tax Amount 10,752\.00 Amount After Tax 2,25,792\.00 Total Amount 2,25,792\.00 GST Reverse Charge N\.A\./.test(t));
ok('intra-state: CGST @ 2.50 % and SGST @ 2.50 % carry the figures, IGST is a dash; reverse charge Yes when it applies; TCS and Round Off only when non-zero', (function () { const x = txt(R({ interState: false, igst: 0, rcm: true })); return /CGST @ 2\.50 % 5,376\.00 SGST @ 2\.50 % 5,376\.00 IGST –/.test(x) && /GST Reverse Charge Yes/.test(x) && !/TCS/.test(t) && !/Round Off/.test(t) && /TCS 2,258\.00/.test(txt(R({ tcs: 2258 }))) && /Round Off \+0\.20/.test(txt(R({ total: 369868.8, grand: 369869 }))); })());
ok('Remarks, an always-present LUT Bond No. line (blank on a domestic sale, the LUT on an export — as the reference prints it), the HSN-wise summary; an export prints the LUT declaration and EXPORT INVOICE', /Remarks/.test(t) && /<b>LUT Bond No\.<\/b> <\/div>/.test(h) && /HSN\/SAC Rate Taxable IGST Amt\. Total tax 25221000 5\.00%/.test(t) && (function () { const x = txt(R({ type: 'export', export: { country: 'Nepal' } })); return /LUT Bond No\. AD080826023319U/.test(x) && /export under LUT without payment of IGST/.test(x) && /Place of Supply Nepal/.test(x) && /EXPORT INVOICE/.test(x); })());
ok('e-invoice: TAX E-INVOICE title, IRN / Ack No / Ack Date; the QR only from the portal\'s signed payload (qrData "x" draws nothing)', !/IRN/.test(t) && (function () { const x = R({ irn: '818d875e443e3c8d340ad284d9eb3d35de8478812a5d34fa107f701f26dad006', ackNo: '172621081606743', ackDt: '02-09-2026 22:49:00', qrData: 'x' }); return /class="w">TAX E-INVOICE</.test(x) && /<span>IRN<\/span><b>818d875e/.test(x) && /<span>Ack No\.<\/span><b>172621081606743/.test(x) && !/qrimg/.test(x.replace(/<style>[\s\S]*?<\/style>/, '')) && /<svg class="qrimg"/.test(R({ irn: 'a'.repeat(64), signedQr: 'eyJhbGciOiJSUzI1NiJ9.' + 'eyJkYXRhIjoiUXVpY2tMaW1lIn0'.repeat(10) + '.c2ln' })); })());
ok('Amount in words, the firm\'s own terms as bullets (no E.&O.E.), For DESHWALI MINERALS · the reference seal · a green tick (owner: "remove MOHAMMAD SALIM, add the tick") · Authorised Signatory & Seal, the registered address in the foot, no unit address until the owner gives one', /Amount in words Rupees Two Lakh Twenty Five Thousand Seven Hundred Ninety Two Only/.test(t) && /<li>Goods once sold will not be taken back or exchanged\.<\/li>/.test(h) && !/O\.E\./.test(t) && /For DESHWALI MINERALS/.test(t) && /<svg class="seal"/.test(h) && /<svg class="tick"/.test(h) && !/MOHAMMAD SALIM/.test(t) && /Authorised Signatory &amp; Seal/.test(h) && /Regd\. Address Near Dharam Kanta Gotan Road, Borunda 342604, Rajasthan/.test(t) && !/Unit/.test(t.slice(t.indexOf('Regd. Address'))) && /Unit Khasra 12, Gotan/.test(txt(R({ seller: Object.assign({}, seller, { unitAddress: 'Khasra 12, Gotan' }) }))));
ok('an e-invoiced sale adds "e-Invoice registered on <ack date>" under the tick — never "Signature valid" (no DSC is applied)', /e-Invoice registered on 02-09-2026 22:49:00/.test(txt(R({ irn: 'a'.repeat(64), ackDt: '2026-09-02 22:49:00' }))) && !/Signature valid/.test(h) && !/registered on/.test(t));
ok('print rules: A4 with no browser margin, a fixed 820px sheet on screen (the app\'s narrow preview zooms it), no page-fill stretching', /@page\{size:A4;margin:0\}/.test(h) && /@media print\{\.sheet\{width:auto;padding:9mm 10mm 6mm\}\}/.test(h) && /\.sheet\{width:820px;margin:0 auto;padding:22px 26px 14px;box-sizing:border-box\}/.test(h) && /@media screen and \(max-width:900px\)\{body\{overflow-x:hidden\}\.sheet\{zoom:\.72\}\}/.test(h));

/* one page, in the browser's own print engine */
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
if (fs.existsSync(chrome)) {
  const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'blueink-'));
  const cases = { one: h, two: R({ items: [{ hsn: '25221000', product: 'Burnt (Calcined) Lime Powder 0-3 mm', qty: 40.96, unit: 'Ton', rate: 5250, rateUnit: 'Ton', taxable: 215040, packing: '50 kg HDPE bags' }], charges: [{ label: 'Transportation charges upto Kharagpur', amount: 137216, hsn: '25221000' }], irn: '818d875e443e3c8d340ad284d9eb3d35de8478812a5d34fa107f701f26dad006', ackNo: '172621081606743', ackDt: '02-09-2026 22:49:00' }), four: R({ items: [1, 2, 3, 4].map(i => ({ hsn: '25221000', product: 'Quick Lime lot ' + i, qty: 10, unit: 'Ton', rate: 5000, rateUnit: 'Ton', taxable: 50000 })) }) };
  Object.keys(cases).forEach(k => {
    const f = path.join(tmp, k + '.html'); fs.writeFileSync(f, cases[k].replace(/src="\/v2\/deshwali-logo\.png"/g, 'src=""').replace(/src="\/v2\/deshwali-lockup-dark\.svg\?v=1"/g, 'src="file://' + __dirname + '/deshwali-lockup-dark.svg"'));
    try { cp.execFileSync(chrome, ['--headless=new', '--disable-gpu', '--no-sandbox', '--print-to-pdf=' + path.join(tmp, k + '.pdf'), 'file://' + f], { stdio: 'ignore', timeout: 60000 }); } catch (e) {}
    const pdf = fs.existsSync(path.join(tmp, k + '.pdf')) ? fs.readFileSync(path.join(tmp, k + '.pdf'), 'latin1') : '';
    const pages = Math.max.apply(null, (pdf.match(/\/Count (\d+)/g) || ['/Count 0']).map(x => +x.slice(7)));
    ok('prints on exactly one A4 page (' + k + ' line case)', pages === 1);
  });
} else console.log('  (Chrome not found — page-count checks skipped)');

console.log('\n  Passed: ' + pass + '   Failed: ' + fail); bad.forEach(n => console.log('    ✗ ' + n));
console.log(fail ? '\n❌ ' + fail + ' FAILED' : '\n✅ ALL ' + pass + ' BLUEINK TESTS PASSED');
process.exit(fail ? 1 : 0);
