/* ═══════════════════════════════════════════════════════════════════════
   Full-page Party Statement — bank-style running account for one party.
   Uses the single-source ledger engine QLD.partyLedger(idx, {from,to}).
   Date-range filter · record receipt against balance · Print/PDF · WhatsApp.
   Opened as ledger.html?party=<idx> (from the CRM drawer).
   ═══════════════════════════════════════════════════════════════════════ */
QLShell.mount({ active: 'parties', title: 'Party Statement' });
const Q = window.QLD, fC = Q.fC;
const esc = s => (s == null ? '' : s).toString().replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const drcr = v => { const a = Math.round(Math.abs(v)); return a < 1 ? '₹0' : fC(a) + ' ' + (v >= 0 ? 'Dr' : 'Cr'); };
function qp(k) { return new URLSearchParams(location.search).get(k); }
function waLink(phone, text) { const d = (phone || '').replace(/\D/g, ''); const n = d.length === 10 ? '91' + d : d; return 'https://wa.me/' + n + '?text=' + encodeURIComponent(text || ''); }
function isMobile() { return window.matchMedia && window.matchMedia('(max-width:768px)').matches; }

let IDX = parseInt(qp('party'), 10); if (isNaN(IDX)) IDX = 0;
let FROM = '', TO = '';

function recordReceipt(p) {
  const isSupp = p.type === 'supplier';
  QLShell.openForm({
    title: isSupp ? 'Record payment made' : 'Record receipt', sub: (p.name || '') + ' · posts to the running balance',
    specs: [
      { k: 'amount', label: (isSupp ? 'Amount paid' : 'Amount received') + ' (₹)', type: 'number', req: true, reqNonZero: true },
      { k: 'date', label: 'Date', type: 'date', req: true },
      { k: 'mode', label: 'Mode', type: 'select', opts: Q.paymentMethods.map(m => [m, m]) },
      { k: 'ref', label: 'Reference no.', ph: 'UTR / cheque / txn id' },
      { k: 'desc', label: 'Note', type: 'textarea', full: true, ph: 'e.g. advance for July dispatch' }
    ],
    initial: { date: new Date().toISOString().slice(0, 10), mode: 'Bank' },
    saveLabel: isSupp ? 'Record payment' : 'Record receipt',
    onSave: v => {
      Q.recordLedgerEntry(IDX, isSupp ? { dr: +v.amount, date: v.date, mode: v.mode, ref: v.ref, desc: v.desc } : { cr: +v.amount, date: v.date, mode: v.mode, ref: v.ref, desc: v.desc });
      QLShell.toast(isSupp ? 'Payment recorded' : 'Receipt recorded', 'ok'); render();
    }
  });
}

function statementDoc(L) {
  const p = L.party, co = Q.co || {};
  const rows = L.rows.map(e => `<tr><td>${Q.fDS(e.date)}</td><td>${esc(e.desc)}${e.ref ? ' · ' + esc(e.ref) : ''}</td><td class="r">${e.dr ? fC(e.dr) : ''}</td><td class="r">${e.cr ? fC(e.cr) : ''}</td><td class="r">${drcr(e.bal)}</td></tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Statement — ${esc(p.name)}</title><style>
    *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;color:#111;margin:26px;font-size:12px}
    h1{font-size:18px;margin:0} .m{color:#666} .hd{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #111;padding-bottom:10px;margin-bottom:12px}
    .pty{font-size:13px;margin:2px 0 8px} .sum{display:flex;flex-wrap:wrap;gap:22px;margin:8px 0 12px;font-size:12px}
    table{width:100%;border-collapse:collapse} th,td{border-bottom:1px solid #ddd;padding:7px 8px;text-align:left} th{background:#f3f4f6;font-size:11px;text-transform:uppercase;letter-spacing:.03em}
    .r{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap} tfoot td{font-weight:bold;border-top:2px solid #111}
  </style></head><body>
    <div class="hd"><div><h1>${esc(co.name || co.short || '')}</h1><div class="m">${co.gstin ? 'GSTIN ' + esc(co.gstin) : ''}${co.state ? ' · ' + esc(co.state) : ''}</div></div>
      <div style="text-align:right"><b>ACCOUNT STATEMENT</b><div class="m">${FROM || 'Beginning'} &rarr; ${TO || 'Today'}</div></div></div>
    <div class="pty"><b>${esc(p.name)}</b>${p.gstin ? ' · GSTIN ' + esc(p.gstin) : ''}${p.phone ? ' · ' + esc(p.phone) : ''}</div>
    <div class="sum"><span>Opening: <b>${drcr(L.openingForRange)}</b></span><span>Total Debit: <b>${fC(Math.round(L.totalDr))}</b></span><span>Total Credit: <b>${fC(Math.round(L.totalCr))}</b></span><span>Closing: <b>${drcr(L.closing)}</b></span></div>
    <table><thead><tr><th>Date</th><th>Particulars</th><th class="r">Debit</th><th class="r">Credit</th><th class="r">Balance</th></tr></thead>
      <tbody>${rows || '<tr><td colspan="5" style="text-align:center;color:#888">No entries</td></tr>'}</tbody>
      <tfoot><tr><td colspan="2">Period total</td><td class="r">${fC(Math.round(L.totalDr))}</td><td class="r">${fC(Math.round(L.totalCr))}</td><td class="r">${drcr(L.closing)}</td></tr></tfoot></table>
    <p class="m" style="margin-top:18px">Running-account statement · generated by ${esc(co.short || 'QuickLimes')}</p>
  </body></html>`;
}
function printStatement(L) {
  const html = statementDoc(L);
  if (isMobile() && window.QLMobile && QLMobile.invoiceViewer) {
    QLMobile.invoiceViewer({ html, printHtml: html, title: 'Statement · ' + (L.party.name || ''), shareText: 'Account statement — ' + (L.party.name || '') });
    return;
  }
  const w = window.open('', '_blank');
  if (w) { w.document.write(html + '<scr' + 'ipt>onload=function(){setTimeout(print,300)}</scr' + 'ipt>'); w.document.close(); }
  else QLShell.toast('Allow pop-ups to print the statement');
}

function card(label, val, col, sub) { return `<div class="lgp-card"><span>${esc(label)}</span><b${col ? ` style="color:${col}"` : ''}>${val}</b>${sub ? `<i style="display:block;font-size:11px;color:var(--ql-text-secondary);font-style:normal;margin-top:3px">${esc(sub)}</i>` : ''}</div>`; }

/* ── Quick ranges — the dates people actually ask for, one tap each ── */
const ymd = d => d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0');
function fyStart(d) { const y = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1; return y + '-04-01'; }
function RANGES() {
  const now = new Date(), m0 = new Date(now.getFullYear(), now.getMonth(), 1);
  const pm = new Date(now.getFullYear(), now.getMonth() - 1, 1), pmEnd = new Date(now.getFullYear(), now.getMonth(), 0);
  return [
    ['All time', '', ''],
    ['This month', ymd(m0), ymd(now)],
    ['Last month', ymd(pm), ymd(pmEnd)],
    ['This FY', fyStart(now), ymd(now)]
  ];
}

/* ── Insights from data the ledger ALREADY has (credit terms, ageing, advance,
   payment behaviour) — nothing invented, every line traceable to a row. ── */
function insights(L) {
  const out = [], p = L.party, bal = L.closing;
  const rows = L.rows || [];
  const unpaidDr = rows.filter(e => e.dr > 0);
  const lastCr = [...rows].reverse().find(e => e.cr > 0);
  const daysBetween = (a, b) => Math.round((new Date(b + 'T00:00') - new Date(a + 'T00:00')) / 864e5);
  const today = ymd(new Date());

  if (bal > 0.5) {
    const oldest = unpaidDr[0];
    if (oldest) {
      const age = daysBetween(oldest.date, today);
      const terms = +p.creditDays || 0;
      if (terms && age > terms) out.push({ t: 'bad', h: `Overdue by ${age - terms} days`, s: `Oldest open entry ${Q.fDS(oldest.date)} · ${terms}-day terms.` });
      else if (age > 60) out.push({ t: 'bad', h: `Oldest balance is ${age} days old`, s: 'No credit terms set for this party.' });
      else out.push({ t: 'warn', h: `${drcr(bal)} outstanding`, s: `Oldest open entry ${Q.fDS(oldest.date)}${terms ? ` · ${terms}-day terms` : ''}.` });
    }
    const lim = +p.creditLimit || 0;
    if (lim && bal > lim) out.push({ t: 'bad', h: `Over the credit limit by ${fC(Math.round(bal - lim))}`, s: `Limit ${fC(lim)}.` });
  } else if (bal < -0.5) {
    out.push({ t: 'good', h: `${fC(Math.round(-bal))} advance held`, s: 'Adjust against the next invoice.' });
  } else if (rows.length) {
    out.push({ t: 'good', h: 'Fully settled', s: 'No outstanding balance for this period.' });
  }

  if (lastCr) out.push({ t: '', h: `Last payment ${fC(Math.round(lastCr.cr))}`, s: `${Q.fDS(lastCr.date)} · ${daysBetween(lastCr.date, today)} days ago.` });
  else if (rows.length) out.push({ t: 'warn', h: 'No payment received yet', s: 'Nothing has been credited in this period.' });

  if (L.totalDr > 0) {
    const pct = Math.round((L.totalCr / L.totalDr) * 100);
    out.push({ t: '', h: `${pct}% of billing collected`, s: `${fC(Math.round(L.totalCr))} received against ${fC(Math.round(L.totalDr))} billed.` });
  }
  return out.slice(0, 4);
}

/* Every cell goes through QLShell.csvRow — the ONE place floats are rounded to
   paise and text is preserved verbatim. Never hand-roll a CSV writer here: the
   raw floats this ledger computes (18.15 × 12385 = 224787.74999999997) would
   otherwise land in the file exactly as the UI never shows them. */
function exportLedger(L) {
  const row = QLShell.csvRow;
  const out = [
    row([L.party.name, L.party.gstin || '']),
    row(['Opening balance', L.openingForRange]),
    row(['Date', 'Particulars', 'Ref', 'Debit', 'Credit', 'Balance']),
    ...L.rows.map(e => row([e.date, e.desc, e.ref || '', e.dr || '', e.cr || '', e.bal])),
    row(['Total', '', '', L.totalDr, L.totalCr, L.closing])
  ];
  QLShell.downloadCSV('Ledger_' + (L.party.name || 'party').replace(/[^\w]+/g, '_'), out.join('\r\n'));
  QLShell.toast('Statement exported — ' + L.rows.length + ' entries', 'ok');
}

function render() {
  const main = document.getElementById('ql-main'); if (!main) return;
  const L = Q.partyLedger(IDX, { from: FROM, to: TO });
  if (!L) { main.innerHTML = `<div class="dash"><div class="page-head"><h1 class="page-title">Statement</h1></div><div class="card" style="padding:28px">Party not found. <a href="parties.html">← Back to customers</a></div></div>`; return; }
  const p = L.party, bal = L.closing;
  const balCol = bal > 0.5 ? 'var(--ql-danger-600)' : bal < -0.5 ? '#16a34a' : 'var(--ql-text)';
  const ins = insights(L);
  const rows = L.rows.map(e => `<tr>
      <td>${Q.fDS(e.date)}</td>
      <td><b>${esc(e.desc)}</b></td>
      <td class="mono">${esc(e.ref || '—')}</td>
      <td class="num">${e.dr ? fC(e.dr) : ''}</td>
      <td class="num" style="color:#16a34a">${e.cr ? fC(e.cr) : ''}</td>
      <td class="num strong" style="color:${e.bal > 0.5 ? '#b91c1c' : e.bal < -0.5 ? '#16a34a' : 'inherit'}">${drcr(e.bal)}</td>
    </tr>`).join('');
  main.innerHTML = `<div class="dash lgp">
    <div class="page-head lgp-head">
      <div>
        <a class="lgp-back" href="parties.html">← Customers</a>
        <h1 class="page-title">${esc(p.name)}</h1>
        <div class="page-sub">${p.gstin ? 'GSTIN ' + esc(p.gstin) : 'No GSTIN'}${p.phone ? ' · ' + esc(p.phone) : ''} · ${(p.type || 'customer')[0].toUpperCase() + (p.type || 'customer').slice(1)} · <b style="color:${balCol}">${drcr(bal)}</b></div>
      </div>
      <div class="lgp-actions">
        ${p.phone ? '<button class="ql-btn ql-btn-secondary" id="lgWa">WhatsApp</button>' : ''}
        <button class="ql-btn ql-btn-secondary" id="lgPrint">Print / PDF</button>
        <button class="ql-btn ql-btn-primary" id="lgRec">${p.type === 'supplier' ? 'Record payment' : 'Record receipt'}</button>
      </div>
    </div>
    <div class="lgp-cards">
      ${card('Opening balance', drcr(L.openingForRange), '', FROM ? 'as on ' + Q.fDS(FROM) : 'start of ledger')}
      ${card('Billed (debit)', fC(Math.round(L.totalDr)), '', L.rows.filter(e => e.dr > 0).length + ' entries')}
      ${card('Received (credit)', fC(Math.round(L.totalCr)), '#16a34a', L.rows.filter(e => e.cr > 0).length + ' payments')}
      ${card('Closing balance', drcr(bal), balCol, bal > 0.5 ? 'they owe you' : bal < -0.5 ? 'advance held' : 'settled')}
    </div>
    ${ins.length ? `<div class="lgp-ai">
      <svg class="lgp-ai-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l1.9 5.5L19.5 9l-5.6 1.5L12 16l-1.9-5.5L4.5 9l5.6-1.5z"/><circle cx="18" cy="18" r="1.4"/><circle cx="5" cy="17" r="1"/></svg>
      <div class="lgp-ai-list">${ins.map(i => `<div class="lgp-ai-i ${i.t}"><b>${esc(i.h)}</b> — ${esc(i.s)}</div>`).join('')}</div>
    </div>` : ''}
    <div class="card lgp-filter">
      ${RANGES().map(r => `<button class="lgp-chip ${FROM === r[1] && TO === r[2] ? 'on' : ''}" data-r="${esc(r[1])}|${esc(r[2])}">${esc(r[0])}</button>`).join('')}
      <span class="lgp-sep"></span>
      <input type="date" id="lgFrom" value="${FROM}" aria-label="From date"><span>→</span><input type="date" id="lgTo" value="${TO}" aria-label="To date">
      <span class="lgp-count">${L.rows.length} entr${L.rows.length === 1 ? 'y' : 'ies'} · <button class="lgp-chip" id="lgExp" style="margin-left:6px">⬇ Export</button></span>
    </div>
    <div class="card lgp-tablewrap">
      <table class="lgp-table">
        <thead><tr><th>Date</th><th>Particulars</th><th>Ref</th><th class="num">Debit</th><th class="num">Credit</th><th class="num">Balance</th></tr></thead>
        <tbody>${rows || '<tr><td colspan="6" class="lgp-empty">No entries in this period.</td></tr>'}</tbody>
        <tfoot><tr><td colspan="3">Period total</td><td class="num">${fC(Math.round(L.totalDr))}</td><td class="num" style="color:#16a34a">${fC(Math.round(L.totalCr))}</td><td class="num strong" style="color:${balCol}">${drcr(bal)}</td></tr></tfoot>
      </table>
    </div>
  </div>`;
  const $ = id => document.getElementById(id);
  if ($('lgFrom')) $('lgFrom').onchange = e => { FROM = e.target.value; render(); };
  if ($('lgTo')) $('lgTo').onchange = e => { TO = e.target.value; render(); };
  document.querySelectorAll('[data-r]').forEach(b => b.onclick = () => { const [f, t] = b.dataset.r.split('|'); FROM = f; TO = t; render(); });
  if ($('lgExp')) $('lgExp').onclick = () => exportLedger(L);
  if ($('lgPrint')) $('lgPrint').onclick = () => printStatement(L);
  if ($('lgRec')) $('lgRec').onclick = () => recordReceipt(p);
  if ($('lgWa')) $('lgWa').onclick = () => {
    const msg = bal > 0.5 ? `Dear ${p.name},\nYour current outstanding balance with ${(Q.co.short || 'us')} is ${fC(Math.round(bal))}. Kindly arrange payment at your convenience. Thank you.` : `Dear ${p.name},\nThank you — your account is clear. We appreciate your business.`;
    window.open(waLink(p.phone, msg), '_blank');
  };
  QLShell.paintWorkspace && QLShell.paintWorkspace();
}

window.__qlRefresh = render;
window.__qlOnSwitchCompany = () => render();
if (Q.init) Q.init(render); else render();
